version: '3.4'

services:
  db:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong1_2Password
      - MSSQL_PID=Express

  logs:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5005:80"

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database=DockerDB
    ports:
      - "5002:80" 

  webstore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - WebAPI=http://api
      - SeqAddress=http://logs
    ports:
      - "80:80"